README.md
Addresses _issues_ portion of https://github.com/ossf/tac/issues/14
and adds slack.
The `Get Involved` section heading comes from the proposed template https://github.com/ossf/project-template/pull/1
=> Add slack and github issues links

README.md
The charter is maintained in the 'foundation' repo.
Signed-off-by: Dan Middleton <dan.middleton@intel.com>
=> Add TAC charter link

working-group-lifecycle.md
The initial draft of the working group life cycle is based on
https://github.com/ossf/tac/issues/13 and TAC discussions leading up to
the 2020-12-01 meeting.
It is intended to satisfy the Open SSF Charter item 6.e.iii:
[The TAC will be responsible for: ...]
"iii) creating, maintaining and amending project lifecycle states, review
procedures and processes;"
Signed-off-by: Dan Middleton <dan.middleton@intel.com>
=> Add Working Group Life Cycle

.github/ISSUE_TEMPLATE/join-the-openssf-github-org.md
Draft for an issue template for adding org/team members.
* A user can request to be added to the GitHub org
* An org can request that we create a new team for their org within the GitHub org
I think the use case we still need to figure out is new individuals in an existing member org. As far as I can tell, unless we make those who are team maintainers for the teams also org admins, they can't add *individuals* to the GitHub org.
=> Update issue template for new org/team

working-group-abilities.md
This builds on @dcmiddle's draft at #44. I tried to simplify out the parts that were closer to consensus from that discussion to get something started.
I tried to not bring up the distinction between Project and Working Group here until we get a better idea on why we need to have one.
=> Add an initial "working group abilities" document.

README.md
The current link points to a Google Doc that doesn't match to what
is documented in WGs GitHub repository. [0]
This commit updates the link accordingly.
[0] https://github.com/ossf/wg-security-tooling#communications
=> Update link to Security Tools WG Meeting Notes

README.md
According to its repository, the Developer Identity Verification WG
has been renamed to Supply Chain Integrity WG. [0]
The Git repository also redirects to the repo named wg-supply-chain-integrity.
This commit updates the table listing WGs accordingly.
[0] https://github.com/ossf/wg-supply-chain-integrity#supply-chain-integrity-wg-formerly-digital-identity-attestation-wg
=> Update list of WGs to include Supply Chain Integrity WG

process/project-lifecycle.md
This PR removes the ambiguity that currently exists in the document by explicitly allowing projects to enter incubation directly.
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>
=> Clarify that Sandbox is optional

process/request_resources.md
Initial draft: Documents how OpenSSF projects can request the resources/benefits outlined in the Project Lifecycle document. cc @AevaOnline for review and input.
Re: Budget Committee requests, projects and members will need to be able to see a calendar of meetings, members and agenda etc to submit requests
=> Create resource request documentation

dco.md
This adds an explanation about DCOs.
I think it'd be helpful for the TAC to briefly state how it
implements the DCO requirement from the OpenSSF charter.
In particular, it should clarify, in a recorded way, its
stance on names. I think it's also useful to explain how
developers can meet the sign-off requirement.
Finally, it explains how other
repos/organizations could do the same thing.
That would make them better prepared if they later became
OpenSSF projects. It also provides a "cheatsheet" for anyone
who has to actually implement this for OpenSSF :-).
Yes, this commit *does* have a "Signed-off-by" entry!
Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>
=> Add DCO statement

process/project-lifecycle.md
Updated version of https://github.com/ossf/tac/pull/123
1. clarify that projects can report either directly to the TAC or to a WG, and add more details about that oversight relationship (eg technical advice, following the OpenSSF values)
2. Adds passing badge for sandbox, silver for incubation, and gold for graduated projects
=> Adds project oversight and OpenSSF badge levels

README.md, organizational-structure-overview.md
The [README.md](https://github.com/ossf/tac/blob/main/README.md) at the root of this repo doesn't list out the projects that are part of the OpenSSF. This PR adds a table with information about those projects.
In addition, this PR removes ambiguity from how sigstore is described within the TAC repo, and represents an affirmation from the TAC that sigstore is officially and unequivocally an OpenSSF project that reports directly to the OpenSSF TAC. This affirmation is supported by the following facts: 
- sigstore joined the OpenSSF as a project reporting directly to the TAC upon a [unanimous vote at the November 16, 2021 meeting](https://github.com/ossf/tac/issues/64) 
-  sigstore community members have [regularly reported to the OpenSSF …
=> Add projects table to README and clarify status of sigstore as an OpenSSF project

elections/tac-and-scir-election-process.md
The procedure for the TAC and SCIR elections has not yet been officially documented. In preparation for the 2023 elections of the TAC and SCIR members, the Election Officials would like to document the entire election process, including the specific timeline for the 2023 elections.
This document is based on the procedure used during the 2022 elections [1], based on discussions in the TAC in preparation for the 2022 election [2].
[1] https://lists.openssf.org/g/openssf-tac/message/406
[2] https://lists.openssf.org/g/openssf-tac/message/364
=> Adding TAC and SCIR election process description and timeline

README.md
The link to the OpenSSF technical charter in the README is broken. This
changes the link to point to the new markdown version of the charter in
the foundation repository.
Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>
=> Fixing link to OpenSSF Charter

README.md
Given there's been discussion of whether the charter perhaps evolves to stagger terms and the election/appointing cadence is still early in its operation, it is useful to be able to see which members came into the board at what time.  Perhaps eventually this shows via the git history, but that too takes time evolve and settle and is less transparent for a typical reader.
=> clarify terms of appointed and elected members

README.md
Election and appointments results have been announced to the TAC mailing list.  The readme is due an update.
=> update TAC member list for the year

README.md
The diagrammer's society has generated a presentation with some of its diagrams. Link to that presentation from the TAC page, to make it easy for people to find that overview with those diagrams.
=> Add a link to a presentation from the Diagrammer's Society

organizational-structure-overview.md
The original link for the "Foundation Charter" was for the [participation agreement](https://cdn.platform.linuxfoundation.org/agreements/openssf.pdf). I changed this to the actual OpenSSF Charter
=> Charter references different link

LICENSE
This is a new attempt to address issue #88 which doesn't require chasing former contributors to get their agreement to change the license. This keeps the Apache license for prior work and only change the license for new one.
This replaces PR #88.
=> Fix license to match charter

technical-vision.md
Per recent discussions at governing board and TAC meetings, the TAC is starting a process to update our technical vision to both:
- help provide greater external clarity on what the foundation wants to achieve in the next few years, and
- help align community & staff against an execution model that helps to deliver on the vision.
This PR aims to start the dialog with some thoughts I've written down based on several conversations over the few weeks; feedback and input from the community is extremely welcome.
Aside: since there can be confusion on the use of the words `{mission,vision,strategy}`, I've included the definitions used below:
- **Mission**: the purpose of the foundation / reason for existence 
- _Note: the foundation's mission is set by the governing board, not the TAC_
- …
=> Update technical vision for OpenSSF

README.md, elections/tac-and-scir-election-process.md, policies/access.md
Closes #153, assuming the tooling should live in a separate repo.
This is just an initial doc to get things started; happy to take any and all feedback.
=> add github management policies dir

policies/access.md
Followup from #155 and https://github.com/ossf/tac/pull/155#discussion_r1202754183
There are currently no dangerous permissions inherently granted by being a member of the github org, and I don't foresee anyone changing that (at all, let alone without broad discussion and TAC approval).
Note: the wording here is "should", intentionally - this paragraph in no way obligates OpenSSF to add anyone to the github org. However, once someone is _in_ the org, they can be freely added to and removed from teams - prior to being in the org, they have to accept an invitation that expires in 7 days, so it's harder to use teams as a self-documenting structure when you have to wait on invitation acceptance.
=> policy: add github org membership section

organizational-structure-overview.md, process/sig-lifecycle.md
For https://github.com/ossf/tac/issues/161
Based on questions raised and community discussion
=> Update SIG lifecycle doc

README.md
It was anticipated that we would have all the charters in a TAC folder but this has not happened and at this point there is no reason to expect it to ever happen. Each TI typically has its charter in its own repo.
=> remove empty charters subdir

.github/actions/spelling/expect.txt, README.md
The SLSA Tooling project has been going on for a long time already but it wasn't properly documented. It has now an homepage as part of the SCI WG. This adds the project to the list.
This also fixes Arnaud's lastname rendering.
=> Add SLSA Tooling project

.github/actions/spelling/advice.md, .github/workflows/spelling.yml
This is an alternative to #201 as proposed in https://github.com/ossf/tac/pull/201#issuecomment-1727940640
* Add commenting on PRs
* Add commenting on push for repositories not in ossf
* Disable failure status reporting
* Only check changed files
* Disable sarif reporting
* Remove update job
* Adjust advice
With these changes, you'll get a comment like this: https://github.com/check-spelling-sandbox/tac/pull/3#issuecomment-1728284295 and no ❌.
=> Tune check-spelling

.github/actions/spelling/expect.txt, README.md, process/project-lifecycle-documents/gittuf_sandbox_stage.md
gittuf is seeking admission to the OpenSSF Sandbox. We aim to be part of the Supply Chain Integrity WG, where we presented gittuf in the August 30th, 2023 meeting.
gittuf implements security controls into Git repositories using existing Git semantics like its support for cryptographic signatures and its content addressed store. By embedding source security policies into the repository, gittuf makes policies transparent that enables _distributed verification_ by all repository users. Further, as gittuf versions and tracks changes to policies using Git semantics, past repository states can be _audited_ against the then-applicable policies.
We believe gittuf meets the Sandbox entry requirements.
gittuf currently has four maintainers across three organizations:
* Aditya Sirish A Yelgundhalli …
=> gittuf OpenSSF Sandbox Application

process/sig-lifecycle.md
Based on feedback from https://github.com/ossf/tac/pull/182
=> Follow-on update to SIG process

process/project-lifecycle.md
This PR addresses issue #204, changing the project lifecycle to accommodate for specification development as well as code development.
Note that this change should be endorsed by the GB with an update of the charter to extend the definition of a Project from "software focused" to "software or specification focused" for clarity.
If adopted, existing groups working on a specification should be "rebranded" accordingly.
=> Accommodate spec development in a Project

process/working-group-lifecycle.md
Introduce Sandbox stage, and rename other stages to: Incubating, Graduated, and Archived to align with other lifecycles.
=> Update WG Lifecycle

process/templates/PROJECT_NAME_archived_stage.md, process/templates/WG_NAME_archived_stage.md, process/templates/WG_NAME_graduation_stage.md, process/templates/WG_NAME_incubating_stage.md, process/templates/WG_NAME_sandbox_stage.md, process/working-group-lifecycle.md
The Project lifecycle documentation provides detailed instructions on how to go at proposing a new project and advancing a project from one stage to another. This PR adds similar instructions for Working Groups.
This also includes fixing a few typos.
=> Add instructions and templates for creating or advancing a WG

organizational-structure-overview.md
This updates the overview to get aligned with the new structure where spec development happens in a Project.
=> Update governance structure overview to include specs as Projects

organizational-structure-overview.md
Upon further review of the organizational structure overview graph I realized it fails to label the projects as such. It actually looks like sigstore is the only project we have!
This PR fixes that.
Some tuning is probably possible to prettify the graph a bit but let's get it right first.
=> Group projects together

process/TI-Gives+Gets.md, process/project-lifecycle.md, process/working-group-lifecycle.md
The current WG lifecycle process docs don't currently require a TAC sponsor until _after_ the sandbox stage has been reached, even though the intent is for WGs the have TAC sponsor _before_ applying for sandbox status. This PR adjusts the WG lifecycle process to reflect that having a TAC sponsor should be a requirement for WGs when applying for the sandbox stage.
=> TAC sponsor should be sandbox stage requirement for WGs

process/project-lifecycle.md
This is not a full fix for #268, but this particular part is inconsistent with our other process docs.
=> Clarify that projects report to the TAC *or* a WG

.github/ISSUE_TEMPLATE/funding_application.yml
This PR removes any reference to the process so that we have a single source of truth in the process documentation. 
The issue template was made before the process documentation but now that that is in place the issue does not need the information and it is best to reference the other location.
=> Issue template for funding references process doc

process/TI-Gives+Gets.md, process/project-lifecycle.md, process/templates/PROJECT_NAME_incubation_stage.md, process/templates/SIG_NAME_incubating_stage.md, process/templates/WG_NAME_incubating_stage.md, process/working-group-lifecycle.md
This updates the TI Gives + Gets incubating gives/requirements to more closely match the lifecycle docs and templates.
Related to #276, #277, #278.
=> Update incubating TI Gives+Gets to match lifecycle/templates

process/project-lifecycle.md, process/sig-lifecycle.md, process/tac-member-R&Rs.md, process/working-group-lifecycle.md
This PR adds details about the scope and role of TAC sponsors in TIs. The main idea is to reduce TAC sponsor involvement as a TI matures through the lifecycle, while also allowing for each TI and TAC sponsor to flexibly determine the engagement. Edits to the TAC R&Rs reflect these details and also specify a process for transitioning between TAC sponsors, if need be. The added clarifications and details are based on the discussion in #263.
Fixes #263
=> Add details about TAC sponsorship expectations in TI lifecycle

CHANGELOG.md, README.md, TI-reports/0000-quarterly-update-template.md, TI-reports/README.md
This PR proposes a solution to issue #326 to submit TI reports via PRs rather than as issues. It is also entirely github based (no dependency on Google doc) although this could be combined if desired.
=> Add infrastructure for TI reports to be submitted via github PR

CHANGELOG.md, elections/tac-and-scir-election-process.md
This PR clarifies several aspects of the election process related to the TAC and SCIR positions, namely:
* Clarifies when and how the appointment by the GB takes place
* Expands on the timeline with clear milestones
* Specifies how the TAC chair and vice chair are elected
* Specifies what happens when a member steps down
* Specifies what happens when one runs for both TAC and SCIR
* Specifies that calls for nominations, registration, and vote need to be sent broadly to all TIs and general forums via email and Slack
This closes PR #237
=> Improve election process and timeline

process/TI Funding Request Process.md
This PR documents the TI funding request submission cycles as announced in [this](https://openssf.org/blog/2024/03/19/how-openssf-technical-initiatives-can-receive-strategic-funding/) blog post. The dates for Q2 were proposed in https://github.com/ossf/tac/issues/336#issuecomment-2135928206
Fixes #336 .
=> Document Q2 2024 TI funding cycle

CHANGELOG.md, process/Technical_Initiative_Lifecycle.md, process/sig-lifecycle.md
When SIGs produce code or specification, they need to be projects, but this was not fully clear before. Aiming to clarify this.
=> Add clarity wrt SIGs that need to be projects

process/project-lifecycle.md
Updated two sections of the life cycle:
1.  added "Baseline - Once Sandbox" link to "Sandbox" -> "Project Responsibilities"
2. added "Baseline - To Become Incubating" link to "Incubating" -> "Incubation Entry Requirements and Considerations"
The links reference to merging security baseline to TAC repo. I will update the links once the baseline merge is complete. https://github.com/ossf/tac/pull/353
=> Update project-lifecycle.md for sandbox to include security baseline

CHANGELOG.md, process/TI-Gives+Gets.md
updated language around badges per stage.
=> Clarifications on Logo entitlement vs. Badge usage

process/security_baseline.md
Only NIST provides parameters for a 521 bit elliptic curve, others (e.g. ECC Brainpool) provide parameters for a 512 bit curve instead.
=> [security_baseline.md] Alter "or" to "to" to denote a range

.gitvote.yml
The team with voting rights is [TAC](https://github.com/orgs/ossf/teams/tac)
If this team is not the correct people, a TI funding voting team could be established.
Fixes: https://github.com/ossf/tac/issues/384
=> Add .gitvote file to activate GH voting on the TAC repo for TI funding request

CHANGELOG.md, process/TAC-Decision-Process.md
Since we're encouraging TIs to document their quarterly TAC updates via GitHub, this PR adds an explicit line to TAC-decision-process.md to document. 
This PR also removes the Blog decision since it doesn't apply to the TAC repo.
=> Add TAC decision type for TI quarterly updates

TI-reports/2024/2024-Q4-ST-WG.md
This contains consolidated input from all of the ST WG subgroups.
=> This is the Security Tooling WG update for the TAC meeting Oct 29.

README.md
Following completion of an audit of our current Technical Initiatives to make the lists current, this update achieves the following:
- Fixes links to most recent meeting notes for several WGs
- Removes inactive WGs: end users and metrics
- Updates some github links in the projects list
- Adds current list of active SIGs
When time permits a future update will be made to review links for project meeting notes and add more data for SIGs where appropriate
=> Update README Working Groups, Projects and SIGs lists and links

CHANGELOG.md, process/templates/PROJECT_NAME_graduation_stage.md, process/templates/PROJECT_NAME_incubation_stage.md
Although we added security baseline requirements to our project lifecycle these requirements have not been added to the project lifecycle templates. This PR fixes that.
=> Add security baseline reqs to project lifecycle templates

EMERITUS.md, README.md
Add community-elected TAC members:
- Bob Callaway, Google
- Michael Lieberman, Kusari
- Zach Steindler, GitHub
ref: https://lists.openssf.org/g/openssf-tac/message/797
Add GB-appointed TAC members:
- Stephen Augustus, Independent — @justaugustus
- Georg Kunz, Ericsson — @gkunz
- Michael Scovetta, Microsoft — @scovetta
ref: https://lists.openssf.org/g/openssf-tac/message/799
The following TAC members are now emeriti:
- Dan Appelquist
- Sarah Evans
cc: @ossf/tac
=> Update TAC members following 2024 elections

README.md, minutes/2024.md
- minutes: Add 2024 archive
- README: Update meeting notes link to 2025 version
cc: @ossf/tac
=> Update meeting notes for 2025 and add 2024 archive

CHANGELOG.md
Follow-up to @lehors' comment in https://github.com/ossf/tac/pull/429#issuecomment-2578510533:
> I'm not sure we should keep maintaining that file but as things stand I should point out that this should have included a new entry into CHANGELOG.md
=> CHANGELOG: Add entry for TAC onboarding document

README.md
The terms for the (re)elected TAC members were off by a year. This PR changes that to reflect the current two-year term for them.
=> Update terms of 2024 community-elected TAC members

README.md
Updating the working groups table in the TAC readme document with two items:
1. updating each groups meeting notes link to 2025 notes
2. The OpenSSF staff has assigned a point-of-contact to each working group for 2025 to help support the group. Added a column to the table to identify the assigned staff contact for each group.
=> Readme wg updates

TI-reports/2024/2024-Q4-BEST-WG.md
This is the Q4 2024 readout to the TAC of the Best Practices WG.
=> Q4 2024 Best Practices WG TAC Update

process/project-lifecycle-documents/model_signing_sandbox_stage.md
Graduate one maintainer to emeritus status, add GitHub handles to all Maintainers, add links to remaining TODO items in the table at the end (and remove the rows that would still be empty)
=> Update model signing documentation

elections/tac-and-scir-election-process.md
Updated election timeline and clarified the GB-appointment process to include them being able to nomiante and pull from the community list.
=> Revise TAC and SCIR election timeline

README.md
In #469, Baseline and Security Insights were proposed to move to the ORBIT WG, but they weren't updated in the top-level README.
=> Move additional projects to ORBIT WG
