- README.md
This is more consistent with the other entries.
> Consistency glitch fix

- README.md
Adding the link per request in #8.
> Add link to meeting notes for the Vulnerability Disclosures WG

- README.md
Signed-off-by: Phil Estes <estesp@amazon.com>
> Update company affiliation

- README.md
I took the names and emails from the TAC list, please let me know
if you'd prefer something else.
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
> Update the TAC list for the new election.

- README.md
Signed-off-by: Bob Callaway <bcallaway@google.com>
> add space to Red Hat

- README.md
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>
> Add a slack invite link.

- process/project-lifecycle.md
Updates the project_lifecycle.md from the working_version_process branch rather than main so will show diff on #95. 
Integrates comments from @AevaOnline in #100.
#100 should be closed and this PR used for discussing project stages and benefits.
> Updates project_lifecycle.md on WIP branch

- process/project-lifecycle.md
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>
> Fix typos and add link to Code of Conduct

- README.md
- organizational-structure-overview.md
Allstar is actually under the Securing Critical Projects WG
Signed-off-by: Jeff Mendoza <jlm@jlm.name>
> Update Allstar WG

- README.md
> Update README.md with SCIR

- process/tac-member-R&Rs.md
Proposed language for TAC Member R&Rs. This proposal pulls from Walli's P&Ps document and attempts to follow the WG Lead R&Rs format.
Open for feedback and patches. Thank you!
> Add TAC Member R&Rs

- process/README.md
Add removed charter language for TAC operations to the TAC Process & Procedures
> Add removed Charter language for TAC operations

- README.md
This PR add OpenVEX to the list of projects.
/cc @SecurityCRob 
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@uservers.net>
> Add OpenVEX to projects list

- README.md
- process/sig-lifecycle.md
- process/templates/SIG_NAME_archived_stage.md
- process/templates/SIG_NAME_graduation_stage.md
- process/templates/SIG_NAME_incubating_stage.md
- process/templates/SIG_NAME_sandbox_stage.md
While SIGs do not require formal TAC approval it would be beneficial to record the SIGs that exist for documentation purposes. This adds instructions and documentation on how to achieve that.
> Add instructions to record SIG creation and stage change

- process/project-lifecycle-documents/sigstore_graduated_stage.md
It is the shared view of the Sigstore Technical Steering Committee that Sigstore meets the requirements of a **Graduated** project within the OpenSSF
This pull request outlines the project's readiness for graduation.
> Sigstore graduation process application

- .github/ISSUE_TEMPLATE/funding_application.yml
- .github/actions/spelling/allow.txt
First draft #257 for an issue template for TI to submit 
Please see below for what the issue template would look like. These are just screenshots since it doesn't render well until the PR is merged. Please provide feedback, or edit the questions directly in this PR.
> issue template for funding

- process/sig-lifecycle-documents/MEMORY_SAFETY_sandbox_stage.md
Hello there!
I (along with @balteravishay) have been leading the Memory Safety SIG under the Best Practices WG. I saw the new process and am submitting a PR to include us as a sandbox SIG :)
> Add memory safety sandbox

- process/TI-Gives+Gets.md
- process/project-lifecycle.md
- process/templates/PROJECT_NAME_graduation_stage.md
- process/templates/SIG_NAME_graduation_stage.md
- process/templates/WG_NAME_graduation_stage.md
This updates the TI Gives + Gets graduating gives/requirements to more closely match the lifecycle docs and templates.
Related to #279 , #280, #281
> Update graduated TI Gives+Gets to match lifecycle/templates

- process/TI-Gives+Gets.md
- process/project-lifecycle.md
- process/templates/PROJECT_NAME_sandbox_stage.md
- process/templates/SIG_NAME_sandbox_stage.md
- process/templates/WG_NAME_sandbox_stage.md
- process/working-group-lifecycle.md
This updates the TI Gives+Gets Sandbox stage gives/requirements to more closely match the lifecycle docs and templates.
Related to #282, #274, #275
> Update sandbox stage TI Gives+Gets to match lifecycle/templates

- .github/ISSUE_TEMPLATE/funding_application.yml
- CHANGELOG.md
Arguably, our second funding cycle was a success with at least two requests approved!
When we went to evaluate the applications, it became clear that an exact funding amount was helpful for budgeting, and it wasn't clear that funding requests should come from a specific OpenSSF TI. These proposed changes aim to make the funding process more clear to applicants.
> Iterate on funding application

- TI-reports/2024/2024-Q3-DEI-WG.md
Ahead of our Q3 TAC update, we've documented our latest and planned activities.
CC @camaleon2016 @Cyber-JiuJiteria
> Add Q3 2024 DEI WG update

- process/project-lifecycle.md
Added security baseline to incubating project responsibilities and graduated project entry requirements.
> Update project-lifecycle.md for Incubating Projects

- process/project-lifecycle.md
Added security baseline to graduated project responsibilities.
> Update project-lifecycle.md for graduated projects

- TI-reports/2024/2024-Q3-AI-ML-WG.md
This is for preparation for the meeting on Sept 3.
> Add AI/ML WG & model signing Q3 report as PR

- elections/tac-and-scir-election-process.md
Adjusted the GB appointed seat timeline back to the original dates.
> Adjusted GB-Appointed Seats Election Timeline.md

- elections/tac-and-scir-election-process.md
Extend election dates to allow more time for nomination and voter registeration
> Extend election dates

- TI-reports/2024/2024-Q4-Repos-WG.md
> Add 2024 Q4 Securing Software Repositories WG TAC update

- README.md
- process/wg-lifecycle-documents/ai_ml_incubating_stage.md
We are already incubating, but we never finalize the lifecycle process. Filling the missing pieces with this PR.
> Add AI/ML WG to the lifecycle documents.

- elections/OpenSSF-TAC-Nomiations-2025.md
Nomination period closed, this is the final list.
> Add 2025 TAC Election nominations

- TI-reports/2024/2024-Q4-Sigstore.md
Closes https://github.com/ossf/tac/issues/412
> Add 2024 Q4 Sigstore Update

- README.md
ref: https://lists.openssf.org/g/openssf-tac/message/802
> Update TAC Chair and Vice Chair for 2025

- README.md
ref: https://www.linkedin.com/posts/stephenaugustus_opensource-ospo-activity-7285386846895833092-OCBm
> Update Stephen Augustus (justaugustus) affiliation

- README.md
Updates projects table to remove (old) meeting notes links and replace with links to project websites where available.
Updates SIG table to remove status and notes columns.
> Cleans up README projects and sig tables

- process/wg-lifecycle-documents/security_tooling_wg_graduation_stage.md
Assisting the Security Tooling WG in documenting its TAC process status.
> Add graduation application for Security Tooling WG

- TI-reports/2025/2025-Q1-Repos-WG.md
For the upcoming TAC meeting Tuesday Feb 4th
> Add 2025 Q1 Securing Repos WG update

- TI-reports/2025/2025-Q2-Repos-WG.md
For the upcoming TAC meeting Tuesday April 29th.
> Add 2025 Q2 Securing Repos WG update

- TI-reports/2025/2025-Q3-Repos-WG.md
For the August 5th TAC meeting
> Add Securing Software Repos WG Q3 update
